services:
  ibis-server:
    image: ghcr.io/canner/wren-engine-ibis:latest
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      ENABLE_MCP_SERVER: "true"
      MCP_PORT: "9000"
    volumes:
      - ./../etc:/usr/src/app/etc
      - ${MDL_WORKSPACE:-../workspace}:/workspace
