version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
  - package-ecosystem: "pip"
    directory: "/ibis-server"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
  - package-ecosystem: "pip"
    directory: "/wren-modeling-py"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
  - package-ecosystem: "cargo"
    directory: "/wren-modeling-rs"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
