version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(java-deps)"
    labels:
      - "dependencies"
      - "java"
      - "v1-engine-changed"
  - package-ecosystem: "pip"
    directory: "/ibis-server"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(ibis-deps)"
    labels:
      - "dependencies"
      - "python"
      - "ibis"
  - package-ecosystem: "pip"
    directory: "/wren-core-py"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(core-py-deps)"
    labels:
      - "dependencies"
      - "python"
  - package-ecosystem: "cargo"
    directory: "/wren-core"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(core-deps)"
    labels:
      - "dependencies"
      - "core"
      - "rust"
