version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(java-deps)"
    labels:
      - "dependencies"
      - "java"
      - "v1-engine-changed"
  - package-ecosystem: "pip"
    directory: "/ibis-server"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(ibis-deps)"
    labels:
      - "dependencies"
      - "python"
      - "ibis"
  - package-ecosystem: "pip"
    directory: "/wren-modeling-py"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(modeling-py-deps)"
    labels:
      - "dependencies"
      - "python"
  - package-ecosystem: "cargo"
    directory: "/wren-modeling-rs"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(modeling-rs-deps)"
    labels:
      - "dependencies"
      - "modeling-rs"
      - "rust"
