default:
    @just --list --unsorted

install:
    poetry install --no-root

build:
    poetry run maturin build

develop:
    poetry run maturin develop

test: develop
    cargo test
    poetry run pytest
