default:
    @just --list --unsorted

install:
    poetry install --no-root

build *args:
    poetry run maturin build {{args}}

develop:
    poetry run maturin develop

test: develop
    cargo test
    poetry run pytest
