version: '3.8'

services:
  engine:
    image: ghcr.io/canner/wren-engine:latest
    platform: ${PLATFORM}
    ports:
      - 8080:8080
      - 7432:7432
      - 8000:8000
    volumes:
      - ./etc:/usr/src/app/etc
