default:
    @just --list --unsorted

build-core:
    cd ../wren-core-py && just install && just build

core-wheel-path := "../wren-core-py/target/wheels/wren_core_py-*.whl"

install-core:
    # just build-core
    # Using pip install to avoid adding wheel to pyproject.toml
    uv pip install --force-reinstall {{ core-wheel-path }}
