default:
    @just --list --unsorted

install:
    poetry install --no-root

build *args:
    poetry run maturin build {{ args }}

develop:
    poetry run maturin develop

test-r:
    cargo test --no-default-features

test-py:
    poetry run pytest

test: test-r test-py

alias fmt := format

format:
    cargo fmt
    poetry run ruff format .
    poetry run ruff check --fix .
    taplo fmt
