default:
    @just --list --unsorted

install:
    poetry install --no-root

env := env("ENV", "dev")
release_flag := if env == "prod" { "--release" } else { "" }

build:
    poetry run maturin build {{ release_flag }}

develop:
    poetry run maturin develop

test-rs:
    cargo test --no-default-features

test-py:
    poetry run pytest

test: test-rs test-py

alias fmt := format

format:
    cargo fmt
    poetry run ruff format .
    poetry run ruff check --fix .
    taplo fmt
