default:
    @just --list --unsorted

install:
    poetry install --no-root

build *args:
    poetry run maturin build {{ args }}

develop:
    poetry run maturin develop

test:
    cargo test --no-default-features
    just develop
    poetry run pytest

alias fmt := format

format:
    cargo fmt
    poetry run ruff format .
    poetry run ruff check --fix .
    taplo fmt
