name: Auto Milestone Assign

on:
  pull_request_target:
    types: [opened]

jobs:
  assign-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Fetch milestone
        id: fetch-milestone
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            milestones = github.rest.issues.listMilestones({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
            });
            return milestones[0].title
      - name: Assign milestone to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                milestone: '${{ steps.fetch-milestone.outputs.result }}',
            })
