name: Stable Release Pull Request

on:
  workflow_dispatch:
    inputs:
      specific_version:
        type: string
        description: Specific version number (Optional). Default will be the current version plus 0.0.1.

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GitHub action bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-python@v5
        with:
          python-version-file: ./ibis-server/pyproject.toml
          cache: 'poetry'
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.7.1
      - name: Upgrade version
        id: version
        working-directory: ibis-server
        run: |
          if [ -n "${{ github.event.inputs.specific_version }}" ]; then
            poetry version --next-phase ${{ github.event.inputs.specific_version }}
          else
            poetry version patch
          fi
          version=$(poetry version | awk '{print $2}')
          echo "value=$version" >> $GITHUB_OUTPUT
      - name: Create release branch
        run: git checkout -b release/${{ steps.version.outputs.value }}
      - name: Commit version upgrade
        run: |
          git add pyproject.toml
          git commit -m "Upgrade ibis version to ${{ steps.version.outputs.value }}"
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Maven Prepare Release
        run: |
          if [ -n "${{ github.event.inputs.specific_version }}" ]; then
            version_number=${{ github.event.inputs.specific_version }}
            ./mvnw release:prepare -B -DreleaseVersion=${{ github.event.inputs.specific_version }}
          else
            version_number=$(./mvnw --quiet help:evaluate -Dexpression=project.version -DforceStdout | sed -n 's/^\(.*\)-SNAPSHOT/\1/p')
            ./mvnw release:prepare -B -DreleaseVersion=${version_number}
          fi
      - name: Push release branch
        run: git push origin release/${{ steps.version.outputs.value }}
      - name: Push tag
        run: git push origin ${{ steps.version.outputs.value }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/${{ steps.version.outputs.value }}
          labels: "release"
          title: "Release ${{ steps.version.outputs.value }}"
          body: |
            :robot: I have created a release ${{ steps.version.outputs.value }}
